### ISSUE TITLE
RoadRunner 2.0 configuration pb

### ISSUE THREAD

**Issue by jcheron** [Lapinskas/roadrunner-ubiquity#28]
Hi @Lapinskas 
The Techempower tests are broken since the upgrade to version 2.
see https://tfb-status.techempower.com/results/6ba8043b-bfc2-47c1-8450-1eb0520ef3ba

The configuration seems to have changed, but I could not get a working result.

I tried to modify as follows, respecting the RoadRunner doc, without success:

```yml
server:
  command: "php-cgi ./.ubiquity/_roadrunner.php"
http:
  address:         "0.0.0.0:8080"
  pool:
    # Set numWorkers to 1 while debugging
    num_workers: ${NUM_WORKERS}
    maxJobs:    0

  # static file serving. remove this section to disable static file serving.
  static:
  # root directory for static file (http would not serve .php and .htaccess files).
    dir:   "."

    # list of extensions for forbid for serving.
    forbid: [".php", ".htaccess", ".yml"]

    always: [".ico", ".html", ".css", ".js"]

  headers:
    response:
      "Server": "RoadRunner"
```

When I launch the server, I get the following errors:

![image](https://user-images.githubusercontent.com/2511052/113751300-1a34c600-970c-11eb-8df3-ab3d99c88f7d.png)

My modifications are on this repo: https://github.com/jcheron/FrameworkBenchmarks/tree/fix-rr-ubiquity

If you have an idea
